In [1]:
import numpy as np

In [2]:
data1=[[1,2,3,4],[5,6,7,8]]

In [3]:
arr1=np.array(data1)

In [4]:
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
arr1.ndim

2

In [6]:
arr1.shape

(2, 4)

In [8]:
arr1.dtype

dtype('int32')

In [9]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
a=np.arange(15)

In [14]:
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
a[5]

5

In [16]:
a[5:8]

array([5, 6, 7])

In [17]:
a[5:8]=12

In [18]:
a

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11, 12, 13, 14])

In [20]:
visu=np.arange(15).reshape(3,5)

In [21]:
visu

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
visu[0]

array([0, 1, 2, 3, 4])

In [23]:
visu[:,0]

array([ 0,  5, 10])

In [24]:
array2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
array2d[2]

array([7, 8, 9])

In [29]:
array2d[0,2]

3

In [30]:
array2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
array2d[2:]

array([[7, 8, 9]])

In [33]:
array2d[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [35]:
array2d[:,0]

array([1, 4, 7])

In [36]:
 array2d[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [37]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
array2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
arr=np.arange(10)

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr1=np.sqrt(arr)

In [43]:
arr1

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [44]:
np.square(arr1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
np.sign(arr1)

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.exp(arr1)

array([ 1.        ,  2.71828183,  4.11325038,  5.65223367,  7.3890561 ,
        9.35646902, 11.58243519, 14.09403011, 16.91882868, 20.08553692])

In [47]:
np.log(arr1)

C:\Users\ASUS\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.34657359, 0.54930614, 0.69314718,
       0.80471896, 0.89587973, 0.97295507, 1.03972077, 1.09861229])

In [48]:
np.floor(arr1)

array([0., 1., 1., 1., 2., 2., 2., 2., 2., 3.])

In [49]:
np.ceil(arr1)

array([0., 1., 2., 2., 2., 3., 3., 3., 3., 3.])

In [52]:
a=[3,4,1]

In [53]:
b=[4,3,1]

In [54]:
np.add(a,b)

array([7, 7, 2])

In [56]:
np.subtract(a,b)

array([-1,  1,  0])

In [57]:
np.multiply(a,b)

array([12, 12,  1])

In [58]:
np.divide(a,b)

array([0.75      , 1.33333333, 1.        ])

In [59]:
np.fmax(a,b)

array([4, 4, 1])

In [60]:
np.fmin(a,b)

array([3, 3, 1])

In [63]:
np.mod(a,b)

array([3, 1, 0], dtype=int32)

In [64]:
np.greater_equal(a,b)

array([False,  True,  True])

In [65]:
np.less_equal(a,b)

array([ True, False,  True])

In [66]:
np.less(a,b)

array([ True, False, False])

In [67]:
np.equal(a,b)

array([False, False,  True])

In [68]:
arrsts=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [69]:
arrsts

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
arrsts.mean()

4.0

In [72]:
arrsts.std()

2.581988897471611

In [73]:
arrsts.var()

6.666666666666667

In [74]:
arrsts.sum()

36

In [75]:
a=np.array([[1,2,3],[2,3,4]])

In [76]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [77]:
z=np.zeros([2,3])

In [78]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.append(a,z,axis=0)

array([[1., 2., 3.],
       [2., 3., 4.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.append(a,z,axis=1)

array([[1., 2., 3., 0., 0., 0.],
       [2., 3., 4., 0., 0., 0.]])